apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
type: kubernetes.io/basic-auth
data:
  POSTGRESQL_DATABASE: postgres 
  POSTGRESQL_USER: postgres 
  POSTGRESQL_HOST: 127.0.0.1
  POSTGRESQL_PORT: 5432
  POSTGRESQL_PASSWORD: $(kubectl get secret --namespace amenities database-postgresql -o jsonpath="{.data.postgres-password}" | base64 -d)
  